% Assignment 5: Advanced Aircraft Noise

clear;

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Array\Array.txt
%
% Auto-generated by MATLAB on 16-Feb-2024 14:20:26

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Array = readtable("Array\Array.txt", opts);

% Convert to output type
Array = table2array(Array);

% Clear temporary variables
clear opts

load('Array\aircraft_noise_data_overhead_2020.mat');

h = 64.87;      % [m]
fs = 40000;     % [Hz]
n_mic = 32;     % [-]

x_mic = Array(:,2);
y_mic = Array(:,3);

%% Main code

figure();
plot(x_mic, y_mic, "o");
hold on
axis equal
% add circle https://stackoverflow.com/a/29194105
r = 1;
c = [0 0];
pos = [c-r 2*r 2*r];

rectangle('Position',pos,'Curvature',[1 1]);

